/**
 * getIntelligenceTiles Lambda — Phase 6.2.5
 *
 * Fetches signal snapshots and returns intelligence tiles for dashboard display.
 * Tiles are projections over precomputed signal snapshots (§10.2).
 *
 * Query patterns:
 *   - By tenant: PK = TENANT#{tenantId}#SNAP
 *   - By owner (via GSI1): GSI1PK = OWNER#{ownerId}#{role}
 *
 * INTEL-002 Phase 6.2.5
 */

const { DynamoDBClient, QueryCommand, ScanCommand } = require('@aws-sdk/client-dynamodb');
const { unmarshall } = require('@aws-sdk/util-dynamodb');
const { getConfig } = require('./config-reader');

const dynamoDB = new DynamoDBClient({});
const STATE_TABLE = process.env.STATE_TABLE_NAME || 'talent-flow-state';
const DISMISSALS_TABLE = process.env.DISMISSALS_TABLE_NAME || 'talent-flow-intelligence-dismissals';

// Default tile generation thresholds (fallback if config unavailable)
// EPIC 1 Task 1.3: Now loaded from config; these are safe defaults
const DEFAULT_THRESHOLDS = {
  OFFER_EXPIRY_URGENT: 3,    // Days - urgent if expiring in 3 days
  FINAL_SCORE_HIGH: 85,      // Score - high performer threshold
  DAYS_STALE: 14,            // Days - candidate stale threshold
};

// ══════════════════════════════════════════════════════════════════════════════
// Rule Configuration with Role Targeting
// Each rule specifies which roles should see tiles generated by it
// ══════════════════════════════════════════════════════════════════════════════
const RULE_CONFIG = {
  // TA-focused rules (pipeline management, candidate engagement)
  'RULE-SLA-001': { targetRoles: ['TA'], name: 'SLA Breached' },
  'RULE-SLA-002': { targetRoles: ['TA'], name: 'SLA At Risk' },
  'RULE-OFFER-001': { targetRoles: ['TA'], name: 'Offer Expiring Soon' },
  'RULE-DROP-001': { targetRoles: ['TA'], name: 'Engagement Falling' },
  'RULE-EVAL-001': { targetRoles: ['TA'], name: 'Evaluation Failed' },
  'RULE-STALE-001': { targetRoles: ['TA'], name: 'Stalled in Stage' },
  'RULE-RISK-001': { targetRoles: ['TA'], name: 'High Risk Candidate' },

  // HM-focused rules (decisions, approvals, feedback)
  'RULE-HIPO-001': { targetRoles: ['HM'], name: 'Strong Candidate Ready' },
  'RULE-DECISION-001': { targetRoles: ['HM'], name: 'Decision Needed' },
  'RULE-APPROVAL-001': { targetRoles: ['HM'], name: 'Approval Stalled' },
  'RULE-FEEDBACK-001': { targetRoles: ['HM'], name: 'Feedback Overdue' },
  'RULE-FASTTRACK-001': { targetRoles: ['HM', 'TA'], name: 'Fast-Track Recommended' },  // EPIC 4
  'RULE-PANEL-001': { targetRoles: ['HM'], name: 'Split Panel - Document Rationale' },  // EPIC 4
  'RULE-COOLING-001': { targetRoles: ['HM', 'TA'], name: 'Candidate Engagement Cooling' },  // EPIC 3
  'RULE-STAGE-001': { targetRoles: ['TA'], name: 'Stalled in Stage' },  // Was missing

  // IT-focused rules (provisioning, onboarding readiness)
  'RULE-ONBOARD-001': { targetRoles: ['IT'], name: 'Onboarding Preparation Needed' },
  'RULE-PROVISION-001': { targetRoles: ['IT'], name: 'Provisioning At Risk' },
  'RULE-EQUIPMENT-001': { targetRoles: ['IT'], name: 'Equipment Not Ordered' },
  'RULE-ACCESS-001': { targetRoles: ['IT'], name: 'Access Not Provisioned' },
};

/**
 * Check if a rule should be visible to a given role
 */
function isRuleVisibleToRole(ruleId, role) {
  if (!role) return true; // No role filter = show all
  const config = RULE_CONFIG[ruleId];
  if (!config) return true; // Unknown rule = show to all
  return config.targetRoles.includes(role);
}

// Stage labels for human-readable display
const STAGE_LABELS = {
  APPLICATION_REVIEW: 'Application Review',
  INTERVIEWING: 'Interviewing',
  EVALUATION: 'Evaluation',
  BACKGROUND_CHECK: 'Background Check',
  OFFER_PREPARATION: 'Offer Preparation',
  OFFER_APPROVAL: 'Offer Approval',
  OFFER_DELIVERY: 'Offer Delivery',
  CONTRACT_SIGNING: 'Contract Signing',
  PRE_BOARDING: 'Pre-Boarding',
  ONBOARDING: 'Onboarding',
};

/**
 * Lambda handler
 */
exports.handler = async (event) => {
  console.info('[getIntelligenceTiles] Invoked', {
    path: event.path,
    queryParams: event.queryStringParameters,
  });

  try {
    const params = event.queryStringParameters || {};
    const tenantId = params.tenantId || 'DEFAULT';
    const role = params.role; // TA | HM | IT
    const ownerId = params.ownerId;
    const limit = parseInt(params.limit, 10) || 100; // Increased from 20 to 100

    // EPIC 1 Task 1.3: Load config-driven thresholds
    let thresholds = DEFAULT_THRESHOLDS;
    try {
      const config = await getConfig(tenantId, 'INTELLIGENCE_RULES');
      if (config?.thresholds) {
        thresholds = { ...DEFAULT_THRESHOLDS, ...config.thresholds };
        console.info('[getIntelligenceTiles] Using config thresholds', { thresholds });
      }
    } catch (configError) {
      console.warn('[getIntelligenceTiles] Config load failed, using defaults', { error: configError.message });
    }

    // Fetch signal snapshots
    const snapshots = await fetchSnapshots(tenantId, { ownerId, role, limit });

    // Generate tiles from snapshots (with role filtering and config thresholds)
    const rawTiles = generateTiles(snapshots, role, thresholds);
    console.info('[DEBUG] After generateTiles', { rawTileCount: rawTiles.length });

    // EPIC 1 Task 1.4: Aggregate-and-route tile model
    // Group tiles → aggregate by rule, promote top 1-3 CRITICAL to per-entity
    const tiles = applyAggregationModel(rawTiles, tenantId, role);
    console.info('[DEBUG] After aggregation', { tileCount: tiles.length });

    // EPIC 1 Task 1.2: Apply dismissal/snooze overlay
    // Extract userId from JWT claims
    const userId = event.requestContext?.authorizer?.jwt?.claims?.sub;

    // Fetch user's dismissal overlay (single query, no N+1)
    const dismissalOverlay = userId ? await fetchDismissalOverlay(userId) : new Map();
    console.info('[DEBUG] Dismissal overlay', { userId, dismissedCount: dismissalOverlay.size });

    // Filter tiles based on dismissal overlay
    const visibleTiles = applyDismissalFilter(tiles, dismissalOverlay);
    console.info('[DEBUG] After dismissal filter', { visibleTileCount: visibleTiles.length });

    // Sort by priority (CRITICAL > HIGH > MEDIUM > LOW)
    const sortedTiles = sortTilesByPriority(visibleTiles);

    console.info('[getIntelligenceTiles] Generated tiles', {
      role,
      snapshotCount: snapshots.length,
      tileCount: sortedTiles.length,
    });

    return response(200, {
      tiles: sortedTiles.slice(0, limit),
      total: sortedTiles.length,
      tenantId,
    });
  } catch (err) {
    console.error('[getIntelligenceTiles] Error', { error: err.message });
    return response(500, { error: 'Failed to fetch intelligence tiles' });
  }
};

/**
 * Fetch signal snapshots from DynamoDB
 */
async function fetchSnapshots(tenantId, opts = {}) {
  const { ownerId, role, limit = 50 } = opts;

  // If ownerId provided, use GSI1 for scoped query
  if (ownerId && role) {
    const result = await dynamoDB.send(new QueryCommand({
      TableName: STATE_TABLE,
      IndexName: 'GSI1',
      KeyConditionExpression: 'GSI1PK = :gsi1pk',
      ExpressionAttributeValues: {
        ':gsi1pk': { S: `OWNER#${ownerId}#${role}` },
      },
      Limit: limit,
      ScanIndexForward: false, // Most recent first
    }));

    return (result.Items || []).map(item => unmarshall(item));
  }

  // Otherwise, query by tenant snapshot partition
  const result = await dynamoDB.send(new QueryCommand({
    TableName: STATE_TABLE,
    KeyConditionExpression: 'PK = :pk AND begins_with(SK, :sk)',
    ExpressionAttributeValues: {
      ':pk': { S: `TENANT#${tenantId}#SNAP` },
      ':sk': { S: 'CAND#' },
    },
    Limit: limit,
  }));

  // Sort by computedAt (most recent first) since DynamoDB sorts by SK (alphabetical)
  const snapshots = (result.Items || []).map(item => unmarshall(item));
  return snapshots.sort((a, b) => {
    const timeA = new Date(a.computedAt || 0).getTime();
    const timeB = new Date(b.computedAt || 0).getTime();
    return timeB - timeA; // Descending (newest first)
  });
}

/**
 * Fetch user's dismissal overlay (EPIC 1 Task 1.2)
 * Returns Map of tileKey → { action, snoozeUntil, snapshotSignature }
 * Single query per request (no N+1)
 */
async function fetchDismissalOverlay(userId) {
  try {
    const result = await dynamoDB.send(new QueryCommand({
      TableName: DISMISSALS_TABLE,
      KeyConditionExpression: 'PK = :pk',
      ExpressionAttributeValues: {
        ':pk': { S: `USER#${userId}` },
      },
      Limit: 100, // Most users won't have more than 100 dismissals
    }));

    const overlay = new Map();
    for (const item of result.Items || []) {
      const record = unmarshall(item);
      // Extract tileKey from SK: "TILEDISMISS#{tileKey}"
      const tileKey = record.SK?.replace(/^TILEDISMISS#/, '');
      if (tileKey) {
        overlay.set(tileKey, {
          action: record.action,
          snoozeUntil: record.snoozeUntil,
          snapshotSignature: record.snapshotSignature,
        });
      }
    }

    return overlay;
  } catch (error) {
    console.warn('[fetchDismissalOverlay] Failed to fetch dismissals - showing all tiles', { error: error.message });
    return new Map(); // Fail open - show all tiles if dismissals unavailable
  }
}

/**
 * Apply aggregate-and-route tile model (EPIC 1 Task 1.4)
 * Groups tiles by rule → creates aggregate tiles with count + routeTarget
 * Promotes top 1-3 CRITICAL tiles to per-entity mode
 */
function applyAggregationModel(rawTiles, tenantId, role) {
  // Group tiles by ruleId
  const ruleGroups = new Map();
  for (const tile of rawTiles) {
    const ruleId = tile.ruleId || 'UNKNOWN';
    if (!ruleGroups.has(ruleId)) {
      ruleGroups.set(ruleId, []);
    }
    ruleGroups.get(ruleId).push(tile);
  }

  const resultTiles = [];

  // Process each rule group
  for (const [ruleId, tiles] of ruleGroups.entries()) {
    // If only 1-2 tiles, or all non-CRITICAL, keep as-is (per-entity)
    if (tiles.length <= 2) {
      for (const tile of tiles) {
        tile.mode = 'per-entity';
      }
      resultTiles.push(...tiles);
      continue;
    }

    // Multiple tiles (3+) → apply aggregation logic
    const criticalTiles = tiles.filter(t => t.priority === 'CRITICAL');
    const nonCriticalTiles = tiles.filter(t => t.priority !== 'CRITICAL');

    // Rank CRITICAL tiles by scoring function
    const rankedCritical = rankTiles(criticalTiles);

    // Promote top 1-3 CRITICAL to per-entity
    const promotedCount = Math.min(3, rankedCritical.length);
    for (let i = 0; i < promotedCount; i++) {
      rankedCritical[i].mode = 'per-entity';
      resultTiles.push(rankedCritical[i]);
    }

    // Aggregate the rest (remaining CRITICAL + all non-CRITICAL)
    const aggregateCandidates = [
      ...rankedCritical.slice(promotedCount),
      ...nonCriticalTiles,
    ];

    if (aggregateCandidates.length > 0) {
      // Create aggregate tile
      const firstTile = aggregateCandidates[0];
      const ruleName = RULE_CONFIG[ruleId]?.name || ruleId;

      const aggregateTile = {
        id: `tile-aggregate-${ruleId}`,
        mode: 'aggregate',
        priority: firstTile.priority,
        title: ruleName,
        description: `${aggregateCandidates.length} items require attention`,
        entityType: firstTile.entityType,
        entityId: null, // No specific entity for aggregate
        entityName: null,
        currentStage: null,
        signals: [],
        actions: [
          {
            id: 'view-all',
            label: 'View All',
            icon: 'pi pi-list',
            type: 'primary',
            route: `/platform/talentflow/candidates`, // Will be enhanced with filters
          },
        ],
        createdAt: new Date().toISOString(),
        ruleId,
        count: aggregateCandidates.length,
        routeTarget: {
          view: 'candidates',
          filters: {
            ruleId,
            role,
            tenantId,
          },
        },
      };

      resultTiles.push(aggregateTile);
    }
  }

  return resultTiles;
}

/**
 * Rank tiles by scoring function (§4.4 design)
 * score = severityWeight + businessImpactWeight + actionabilityWeight - ageDecay
 */
function rankTiles(tiles) {
  return [...tiles].sort((a, b) => {
    const scoreA = calculateTileScore(a);
    const scoreB = calculateTileScore(b);
    return scoreB - scoreA; // Descending
  });
}

/**
 * Calculate tile ranking score (§4.4 design)
 */
function calculateTileScore(tile) {
  // Severity weight
  const severityWeights = { CRITICAL: 100, HIGH: 60, MEDIUM: 30, LOW: 10 };
  let score = severityWeights[tile.priority] || 0;

  // Business impact weight (based on ruleId pattern)
  if (tile.ruleId?.includes('OFFER') || tile.ruleId?.includes('ONBOARD')) {
    score += 40; // Offer/onboarding highest impact
  } else if (tile.ruleId?.includes('SLA') || tile.ruleId?.includes('PROVISION')) {
    score += 30; // Time-sensitive operations
  } else if (tile.ruleId?.includes('EVAL') || tile.ruleId?.includes('DECISION')) {
    score += 20; // Decision points
  } else {
    score += 10; // Housekeeping/general
  }

  // Actionability weight (tiles with primary actions score higher)
  if (tile.actions?.some(a => a.type === 'primary')) {
    score += 15;
  }

  // Age decay (tiles older than 24h get slight penalty)
  const ageHours = (Date.now() - new Date(tile.createdAt).getTime()) / (1000 * 60 * 60);
  if (ageHours > 24) {
    score -= Math.min(20, Math.floor(ageHours / 24) * 2); // -2 per day, max -20
  }

  return score;
}

/**
 * Apply dismissal/snooze filter to tiles (EPIC 1 Task 1.2)
 * Filters out dismissed/snoozed tiles based on user's overlay
 */
function applyDismissalFilter(tiles, dismissalOverlay) {
  const now = new Date().toISOString();

  return tiles.filter(tile => {
    // Compute tileKey from tile.entityId and tile.ruleId
    const tileKey = `${tile.entityId}#${tile.ruleId}`;

    // Check if user has a dismissal record for this tileKey
    const dismissal = dismissalOverlay.get(tileKey);
    if (!dismissal) {
      return true; // No dismissal → show tile
    }

    // Compute current snapshotSignature (for now, use tileKey)
    // In future: hash of actual condition so recurring issues resurface
    const currentSignature = tileKey;

    // Check action type
    if (dismissal.action === 'DISMISS') {
      // Skip if signature matches (same condition still active)
      if (dismissal.snapshotSignature === currentSignature) {
        return false; // Hide tile
      }
      // If signature changed (condition cleared and re-triggered), show tile
      return true;
    }

    if (dismissal.action === 'SNOOZE') {
      // Skip if snooze window hasn't expired yet
      if (dismissal.snoozeUntil && now < dismissal.snoozeUntil) {
        return false; // Hide tile until snoozeUntil
      }
      // Snooze expired → show tile
      return true;
    }

    if (dismissal.action === 'ACKNOWLEDGE') {
      // Acknowledge doesn't hide the tile (just records user saw it)
      // Future: could add "don't show again" behavior for ACK
      return true;
    }

    // Unknown action → show tile
    return true;
  });
}

/**
 * Generate intelligence tiles from signal snapshots
 * Applies business rules to create actionable tiles
 * Filters by role if provided
 * @param {Array} snapshots - Signal snapshots to process
 * @param {string|null} role - Optional role filter (TA|HM|IT)
 * @param {Object} thresholds - Config-driven thresholds (EPIC 1 Task 1.3)
 */
function generateTiles(snapshots, role = null, thresholds = DEFAULT_THRESHOLDS) {
  const tiles = [];

  for (const snapshot of snapshots) {
    if (!snapshot.signals) continue;

    const signals = snapshot.signals;
    const entityName = snapshot.entityName || 'Unknown';

    // Rule 1: SLA Breached (CRITICAL)
    if (signals.SLA_STATUS === 'BREACHED') {
      tiles.push(createTile(snapshot, {
        priority: 'CRITICAL',
        title: 'SLA Breached',
        description: `${entityName} has breached SLA threshold — immediate action required`,
        ruleId: 'RULE-SLA-001',
      }));
    }

    // Rule 2: SLA At Risk (HIGH)
    else if (signals.SLA_STATUS === 'AT_RISK') {
      tiles.push(createTile(snapshot, {
        priority: 'HIGH',
        title: 'SLA At Risk',
        description: `${entityName} is approaching SLA threshold`,
        ruleId: 'RULE-SLA-002',
      }));
    }

    // Rule 3: Offer Expiring Soon (CRITICAL/HIGH)
    const daysToExpiry = signals.OFFER_DAYS_TO_EXPIRY;
    if (daysToExpiry !== null && daysToExpiry !== undefined &&
        daysToExpiry <= thresholds.OFFER_EXPIRY_URGENT && daysToExpiry >= 0) {
      tiles.push(createTile(snapshot, {
        priority: daysToExpiry <= 1 ? 'CRITICAL' : 'HIGH',
        title: 'Offer Expiring Soon',
        description: `Offer for ${entityName} expires in ${daysToExpiry} day${daysToExpiry !== 1 ? 's' : ''}`,
        ruleId: 'RULE-OFFER-001',
      }));
    }

    // Rule 4: High Score Candidate Ready (MEDIUM) - Only for non-HM stages
    // HM sees this via RULE-HIPO-001 in the HM-specific section
    const finalScore = signals.FINAL_SCORE;
    // Skip - handled in HM-specific section below

    // Rule 5: Engagement Falling (HIGH)
    const engagementSentiment = signals.ENGAGEMENT_SENTIMENT;
    if (engagementSentiment === 'HESITANT' || engagementSentiment === 'DISENGAGED') {
      tiles.push(createTile(snapshot, {
        priority: 'HIGH',
        title: 'Engagement Falling',
        description: `${entityName} showing ${engagementSentiment.toLowerCase()} signals`,
        ruleId: 'RULE-DROP-001',
      }));
    }

    // Rule 6: Evaluation Failed (MEDIUM)
    if (signals.EVALUATION_RESULT === 'FAILED') {
      tiles.push(createTile(snapshot, {
        priority: 'MEDIUM',
        title: 'Evaluation Failed',
        description: `${entityName} did not pass evaluation — review recommended`,
        ruleId: 'RULE-EVAL-001',
      }));
    }

    // ══════════════════════════════════════════════════════════════════════════
    // Phase 6.4: Composite Signal Rules
    // ══════════════════════════════════════════════════════════════════════════

    // Rule 7: High Risk Candidate (CRITICAL/HIGH based on score)
    const riskScore = signals.CANDIDATE_RISK_SCORE;
    if (riskScore !== null && riskScore !== undefined && riskScore >= 60) {
      tiles.push(createTile(snapshot, {
        priority: riskScore >= 80 ? 'CRITICAL' : 'HIGH',
        title: 'High Risk Candidate',
        description: `${entityName} has risk score of ${riskScore}% — multiple factors require attention`,
        ruleId: 'RULE-RISK-001',
      }));
    }

    // Rule 8: Stalled in Stage (HIGH) - only if risk score didn't already flag it
    const daysInStage = signals.DAYS_IN_CURRENT_STAGE;
    if (daysInStage !== null && daysInStage !== undefined &&
        daysInStage >= thresholds.DAYS_STALE && riskScore < 60) {
      tiles.push(createTile(snapshot, {
        priority: 'HIGH',
        title: 'Stalled in Stage',
        description: `${entityName} has been in ${snapshot.currentStage?.replace(/_/g, ' ') || 'current stage'} for ${daysInStage} days`,
        ruleId: 'RULE-STALE-001',
      }));
    }

    // Rule 9: Onboarding Not Ready (HIGH) - for pre-boarding/onboarding candidates
    const onboardingReadiness = signals.ONBOARDING_READINESS;
    if (onboardingReadiness !== null && onboardingReadiness !== undefined &&
        onboardingReadiness < 75 &&
        ['PRE_BOARDING', 'ONBOARDING'].includes(snapshot.currentStage)) {
      tiles.push(createTile(snapshot, {
        priority: onboardingReadiness < 50 ? 'HIGH' : 'MEDIUM',
        title: 'Onboarding Preparation Needed',
        description: `${entityName} is ${onboardingReadiness}% ready for onboarding — items pending`,
        ruleId: 'RULE-ONBOARD-001',
      }));
    }

    // ══════════════════════════════════════════════════════════════════════════
    // HM-specific Rules
    // ══════════════════════════════════════════════════════════════════════════

    // Rule 10: Decision Needed - candidate in HM_REVIEW stage
    if (snapshot.currentStage === 'HM_REVIEW' || snapshot.currentStage === 'EVALUATION') {
      const daysInStage = signals.DAYS_IN_CURRENT_STAGE || 0;
      if (daysInStage >= 3) {
        tiles.push(createTile(snapshot, {
          priority: daysInStage >= 7 ? 'HIGH' : 'MEDIUM',
          title: 'Decision Needed',
          description: `${entityName} has been awaiting decision for ${daysInStage} days`,
          ruleId: 'RULE-DECISION-001',
        }));
      }
    }

    // Rule 11: Strong candidate for fast-track (HM visibility)
    if (finalScore !== null && finalScore !== undefined && finalScore >= thresholds.FINAL_SCORE_HIGH) {
      tiles.push(createTile(snapshot, {
        priority: 'MEDIUM',
        title: 'Strong Candidate - Fast Track',
        description: `${entityName} scored ${finalScore}% — consider expediting decision`,
        ruleId: 'RULE-HIPO-001',
      }));
    }

    // ══════════════════════════════════════════════════════════════════════════
    // IT-specific Rules
    // ══════════════════════════════════════════════════════════════════════════

    // Rule 12: Provisioning at risk - start date approaching
    const daysToStart = signals.DAYS_TO_START_DATE;
    if (daysToStart !== null && daysToStart !== undefined && daysToStart <= 10 &&
        ['PRE_BOARDING', 'ONBOARDING'].includes(snapshot.currentStage)) {
      tiles.push(createTile(snapshot, {
        priority: daysToStart <= 5 ? 'CRITICAL' : 'HIGH',
        title: 'Provisioning At Risk',
        description: `${entityName} starts in ${daysToStart} days — ensure provisioning complete`,
        ruleId: 'RULE-PROVISION-001',
      }));
    }

    // Rule 13: Equipment not ordered
    const equipmentStatus = signals.EQUIPMENT_REQUEST_STATUS;
    if (equipmentStatus === 'NOT_ORDERED' || equipmentStatus === 'PENDING') {
      if (['PRE_BOARDING', 'ONBOARDING', 'CONTRACT_SIGNING'].includes(snapshot.currentStage)) {
        tiles.push(createTile(snapshot, {
          priority: 'HIGH',
          title: 'Equipment Not Ordered',
          description: `Equipment for ${entityName} has not been ordered`,
          ruleId: 'RULE-EQUIPMENT-001',
        }));
      }
    }

    // Rule 14: Access not provisioned
    const accessProvisioned = signals.ACCESS_PROVISIONED;
    if (accessProvisioned === false &&
        ['PRE_BOARDING', 'ONBOARDING'].includes(snapshot.currentStage)) {
      tiles.push(createTile(snapshot, {
        priority: 'HIGH',
        title: 'Access Not Provisioned',
        description: `System access for ${entityName} has not been set up`,
        ruleId: 'RULE-ACCESS-001',
      }));
    }

    // ══════════════════════════════════════════════════════════════════════════
    // EPIC 4 Rules (Advanced Intelligence Signals)
    // ══════════════════════════════════════════════════════════════════════════

    // Rule 15: Fast-Track Recommended (EPIC 4 TASK 4.3)
    // High score + high consensus + falling engagement = urgent decision
    if (finalScore !== null && finalScore !== undefined && finalScore >= thresholds.FINAL_SCORE_HIGH &&
        signals.PANEL_CONSENSUS?.label === 'HIGH' &&
        signals.ENGAGEMENT_TREND === 'FALLING') {
      tiles.push(createTile(snapshot, {
        priority: 'CRITICAL', // CRITICAL so it gets promoted to per-entity display
        title: 'Fast-Track Recommended',
        description: `${entityName} • High score (${finalScore}) + strong panel consensus + engagement cooling — recommend urgent decision`,
        ruleId: 'RULE-FASTTRACK-001',
      }));
    }

    // Rule 16: Split Panel - Document Rationale (EPIC 4 TASK 4.1)
    // Panel has strong disagreement - requires escalation/documentation
    if (signals.PANEL_SPLIT_FLAG === true) {
      tiles.push(createTile(snapshot, {
        priority: 'CRITICAL', // CRITICAL so it gets promoted to per-entity display
        title: 'Split Panel - Document Rationale',
        description: `${entityName} • Panel strongly disagrees — document decision rationale required`,
        ruleId: 'RULE-PANEL-001',
        acknowledgeOnly: true, // Cannot be dismissed, only acknowledged
      }));
    }

    // Rule 17: Approval Stalled (EPIC 4 TASK 4.2)
    // Offer stuck in approval workflow
    const approvalStepAge = signals.APPROVAL_STEP_AGE;
    if (approvalStepAge !== null && approvalStepAge !== undefined && approvalStepAge >= 5) {
      tiles.push(createTile(snapshot, {
        priority: approvalStepAge >= 7 ? 'HIGH' : 'MEDIUM',
        title: 'Approval Stalled',
        description: `${entityName} • Offer approval stuck in ${snapshot.currentApprovalStep || 'current step'} for ${approvalStepAge} days`,
        ruleId: 'RULE-APPROVAL-001',
      }));
    }

    // Rule 18: Candidate Engagement Cooling (EPIC 3 TASK 3.2)
    // Candidate engagement dropping + no recent response = ghosting risk
    if (signals.ENGAGEMENT_TREND === 'FALLING' &&
        signals.CANDIDATE_DAYS_SINCE_RESPONSE !== null &&
        signals.CANDIDATE_DAYS_SINCE_RESPONSE >= 7) {
      tiles.push(createTile(snapshot, {
        priority: 'MEDIUM',
        title: 'Candidate Engagement Cooling',
        description: `${entityName} • Engagement falling + ${signals.CANDIDATE_DAYS_SINCE_RESPONSE} days since last response — ghosting risk`,
        ruleId: 'RULE-COOLING-001',
      }));
    }

    // Rule 19: Pending Feedback (EPIC 4 TASK 4.1)
    // Panel members haven't submitted feedback
    const pendingCount = signals.PANEL_FEEDBACK_PENDING_COUNT;
    if (pendingCount !== null && pendingCount !== undefined && pendingCount > 0) {
      tiles.push(createTile(snapshot, {
        priority: pendingCount >= 3 ? 'HIGH' : 'MEDIUM',
        title: 'Feedback Overdue',
        description: `${entityName} • ${pendingCount} panel member${pendingCount > 1 ? 's have' : ' has'} not submitted feedback`,
        ruleId: 'RULE-FEEDBACK-001',
      }));
    }
  }

  // Filter tiles by role if specified
  if (role) {
    return tiles.filter(tile => isRuleVisibleToRole(tile.ruleId, role));
  }

  return tiles;
}

/**
 * Create a tile object from snapshot and rule metadata
 */
function createTile(snapshot, opts) {
  const signals = snapshot.signals || {};

  const tile = {
    id: `tile-${snapshot.entityId}-${opts.ruleId}`,
    priority: opts.priority,
    title: opts.title,
    description: opts.description,
    entityType: snapshot.entityType,
    entityId: snapshot.entityId,
    entityName: snapshot.entityName || 'Unknown',
    currentStage: snapshot.currentStage,
    signals: extractDisplaySignals(snapshot),
    actions: getDefaultActions(snapshot),
    createdAt: snapshot.computedAt,
    ruleId: opts.ruleId,
  };

  // Add acknowledgeOnly flag if specified
  if (opts.acknowledgeOnly) {
    tile.acknowledgeOnly = true;
  }

  return tile;
}

/**
 * Extract displayable signal pills for tile
 */
function extractDisplaySignals(snapshot) {
  const signals = [];
  const s = snapshot.signals || {};

  if (snapshot.currentStage) {
    signals.push({
      label: 'Stage',
      value: STAGE_LABELS[snapshot.currentStage] || snapshot.currentStage,
      type: 'info',
    });
  }

  if (s.SLA_STATUS) {
    signals.push({
      label: 'SLA',
      value: s.SLA_STATUS,
      type: s.SLA_STATUS === 'BREACHED' ? 'error' : s.SLA_STATUS === 'AT_RISK' ? 'warning' : 'success',
    });
  }

  if (s.FINAL_SCORE !== null && s.FINAL_SCORE !== undefined) {
    const score = s.FINAL_SCORE;
    signals.push({
      label: 'Score',
      value: `${score}%`,
      type: score >= 85 ? 'success' : score >= 60 ? 'info' : 'warning',
    });
  }

  // Phase 6.4: Composite signal pills
  if (s.CANDIDATE_RISK_SCORE !== null && s.CANDIDATE_RISK_SCORE !== undefined && s.CANDIDATE_RISK_SCORE >= 40) {
    const risk = s.CANDIDATE_RISK_SCORE;
    signals.push({
      label: 'Risk',
      value: `${risk}%`,
      type: risk >= 80 ? 'error' : risk >= 60 ? 'warning' : 'info',
    });
  }

  if (s.DAYS_IN_CURRENT_STAGE !== null && s.DAYS_IN_CURRENT_STAGE !== undefined && s.DAYS_IN_CURRENT_STAGE >= 7) {
    signals.push({
      label: 'In Stage',
      value: `${s.DAYS_IN_CURRENT_STAGE}d`,
      type: s.DAYS_IN_CURRENT_STAGE >= 14 ? 'warning' : 'info',
    });
  }

  if (s.ONBOARDING_READINESS !== null && s.ONBOARDING_READINESS !== undefined) {
    signals.push({
      label: 'Ready',
      value: `${s.ONBOARDING_READINESS}%`,
      type: s.ONBOARDING_READINESS >= 75 ? 'success' : s.ONBOARDING_READINESS >= 50 ? 'warning' : 'error',
    });
  }

  return signals;
}

/**
 * Get default actions for a tile
 */
function getDefaultActions(snapshot) {
  return [
    {
      id: 'view',
      label: 'View',
      icon: 'pi pi-eye',
      type: 'primary',
      route: `/platform/talentflow/candidates/${snapshot.entityId}`,
    },
  ];
}

/**
 * Sort tiles by priority
 */
function sortTilesByPriority(tiles) {
  const priorityOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
  return [...tiles].sort((a, b) =>
    (priorityOrder[a.priority] ?? 4) - (priorityOrder[b.priority] ?? 4)
  );
}

/**
 * Build HTTP response
 */
function response(statusCode, body) {
  return {
    statusCode,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': 'Content-Type,Authorization',
    },
    body: JSON.stringify(body),
  };
}
